In [2]:
import pandas as pd
import math as math
from numpy import sqrt
from numpy import asarray
from pandas import read_csv
from tensorflow.keras import Sequential
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from scipy.special import boxcox, inv_boxcox

import numpy as np
import tensorflow as tf
from sklearn.model_selection import TimeSeriesSplit

In [3]:
data = pd.read_csv(r"C:\Users\patte\Documents\apps\covidLSTM\COVID-19\csse_covid_19_data\csse_covid_19_time_series\time_series_covid19_confirmed_global.csv");

In [4]:
data.loc[data['Country/Region'] == 'China']

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20
49,Anhui,China,31.8257,117.2264,1,9,15,39,60,70,...,990,990,990,990,990,990,990,990,990,990
50,Beijing,China,40.1824,116.4142,14,22,36,41,68,80,...,436,437,442,452,456,469,480,491,504,522
51,Chongqing,China,30.0572,107.8740,6,9,27,57,75,110,...,576,576,576,576,576,576,576,576,576,577
52,Fujian,China,26.0789,117.9874,1,5,10,18,35,59,...,296,296,296,296,296,296,296,299,303,313
53,Gansu,China,37.8099,101.0583,0,2,2,4,7,14,...,127,129,133,133,133,133,134,134,134,136
54,Guangdong,China,23.3417,113.4244,26,32,53,78,111,151,...,1356,1356,1360,1361,1364,1370,1378,1395,1400,1413
55,Guangxi,China,23.8298,108.7881,2,5,23,23,36,46,...,252,252,252,252,253,253,253,254,254,254
56,Guizhou,China,26.8154,106.8748,1,3,3,4,5,7,...,146,146,146,146,147,146,146,146,146,146
57,Hainan,China,19.1959,109.7453,4,5,8,19,22,33,...,168,168,168,168,168,168,168,168,168,168
58,Hebei,China,39.5490,116.1306,1,1,2,8,13,18,...,318,318,318,318,318,318,318,318,318,319
59,Heilongjiang,China,47.8620,127.7615,0,2,4,9,15,21,...,482,482,482,482,482,482,483,484,484,484
60,Henan,China,33.8820,113.6140,5,5,9,32,83,128,...,1273,1273,1273,1273,1273,1273,1273,1273,1273,1274
61,Hong Kong,China,22.3000,114.2000,0,2,2,5,8,8,...,134,140,145,155,162,181,208,256,273,317
62,Hubei,China,30.9756,112.2707,444,444,549,761,1058,1423,...,67786,67790,67794,67798,67799,67800,67800,67800,67800,67800
63,Hunan,China,27.6104,111.7088,4,9,24,43,69,100,...,1018,1018,1018,1018,1018,1018,1018,1018,1018,1018
64,Inner Mongolia,China,44.0935,113.9448,0,0,1,7,7,11,...,75,75,75,75,75,75,75,75,75,75
65,Jiangsu,China,32.9711,119.4550,1,5,9,18,33,47,...,631,631,631,631,631,631,631,631,631,633
66,Jiangxi,China,27.6140,115.7221,2,7,18,18,36,72,...,935,935,935,935,935,935,935,935,935,936
67,Jilin,China,43.6661,126.1923,0,1,3,4,4,6,...,93,93,93,93,93,93,93,93,93,93
68,Liaoning,China,41.2956,122.6085,2,3,4,17,21,27,...,125,125,125,125,125,125,125,126,126,127
69,Macau,China,22.1667,113.5500,1,2,2,2,5,6,...,10,10,10,11,12,15,17,17,18,24
70,Ningxia,China,37.2692,106.1655,1,1,2,3,4,7,...,75,75,75,75,75,75,75,75,75,75
71,Qinghai,China,35.7452,95.9956,0,0,0,1,1,6,...,18,18,18,18,18,18,18,18,18,18
72,Shaanxi,China,35.1917,108.8701,0,3,5,15,22,35,...,245,245,245,245,246,246,246,247,248,248
73,Shandong,China,36.3427,118.1498,2,6,15,27,46,75,...,760,760,760,760,761,761,761,762,764,767
74,Shanghai,China,31.2020,121.4491,9,16,20,33,40,53,...,346,353,353,355,358,361,363,371,380,404
75,Shanxi,China,37.5777,112.2922,1,1,1,6,9,13,...,133,133,133,133,133,133,133,133,133,133
76,Sichuan,China,30.6171,102.7103,5,8,15,28,44,69,...,539,539,539,539,540,540,540,541,542,543
77,Tianjin,China,39.3054,117.3230,4,4,8,10,14,23,...,136,136,136,136,136,136,137,137,137,137
78,Tibet,China,31.6927,88.0924,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
79,Xinjiang,China,41.1129,85.2401,0,2,2,3,4,5,...,76,76,76,76,76,76,76,76,76,76
80,Yunnan,China,24.9740,101.4870,1,2,5,11,16,26,...,174,174,174,176,176,176,176,176,176,176
81,Zhejiang,China,29.1832,120.0934,10,27,43,62,104,128,...,1215,1227,1231,1231,1232,1232,1233,1234,1236,1238

In [197]:
china_data = data.loc[data['Country/Region'] == 'China'];
korea_data = data.loc[data['Country/Region'] == 'Korea, South'];

In [198]:
del china_data['Country/Region']
del china_data['Lat'];
del china_data['Long'];
del korea_data['Lat']
del korea_data['Long']
del korea_data['Province/State']

In [199]:
china_data = china_data.melt(id_vars=['Province/State'], var_name='Date', value_name='Confirmed Cases');
korea_data = korea_data.melt(id_vars=['Country/Region'], var_name='Date', value_name='Confirmed Cases');

In [200]:
## Data prep for China
china_data['Date'] = pd.to_datetime(china_data['Date']);
china_data_transformed = china_data.pivot(index='Date', columns='Province/State', values='Confirmed Cases');
# del china_data_transformed['Tibet']
# del china_data_transformed['Qinghai']
# china_total = pd.DataFrame()
# china_total['China Total Confirmed Cases'] = china_data_transformed.sum(axis=1)
# china_total

            China Total Confirmed Cases
Date
2020-01-22                          548
2020-01-23                          643
2020-01-24                          920
2020-01-25                         1405
2020-01-26                         2074
...                                 ...
2020-03-18                        81083
2020-03-19                        81137
2020-03-20                        81231
2020-03-21                        81286
2020-03-22                        81416

[61 rows x 1 columns]

In [7]:
## Data prep for Korea
korea_data['Date'] = pd.to_datetime(korea_data['Date']);
korea_data = korea_data.pivot(index='Date', columns='Country/Region', values='Confirmed Cases');
korea_total = pd.DataFrame()
korea_total['Korean Total Confirmed Cases'] = korea_data.sum(axis=1)
korea_total

            Korean Total Confirmed Cases
Date
2020-01-22                             1
2020-01-23                             1
2020-01-24                             2
2020-01-25                             2
2020-01-26                             3
2020-01-27                             4
2020-01-28                             4
2020-01-29                             4
2020-01-30                             4
2020-01-31                            11
2020-02-01                            12
2020-02-02                            15
2020-02-03                            15
2020-02-04                            16
2020-02-05                            19
2020-02-06                            23
2020-02-07                            24
2020-02-08                            24
2020-02-09                            25
2020-02-10                            27
2020-02-11                            28
2020-02-12                            28
2020-02-13                            28
2020-02-14                            28
2020-02-15                            28
2020-02-16                            29
2020-02-17                            30
2020-02-18                            31
2020-02-19                            31
2020-02-20                           104
2020-02-21                           204
2020-02-22                           433
2020-02-23                           602
2020-02-24                           833
2020-02-25                           977
2020-02-26                          1261
2020-02-27                          1766
2020-02-28                          2337
2020-02-29                          3150
2020-03-01                          3736
2020-03-02                          4335
2020-03-03                          5186
2020-03-04                          5621
2020-03-05                          6088
2020-03-06                          6593
2020-03-07                          7041
2020-03-08                          7314
2020-03-09                          7478
2020-03-10                          7513
2020-03-11                          7755
2020-03-12                          7869
2020-03-13                          7979
2020-03-14                          8086
2020-03-15                          8162
2020-03-16                          8236
2020-03-17                          8320
2020-03-18                          8413
2020-03-19                          8565

In [8]:
## Standardization
def normalizeData(data):
    scaler = MinMaxScaler().fit(data)
    data = scaler.transform(data)
    return data, scaler

def split_sequence(sequence, n_steps):
    len_seq = sequence.shape[1]
    X, y = list(), list()
    for i in range(len_seq):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len_seq-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[:, i:end_ix], sequence[:, end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return asarray(X), asarray(y)

In [11]:
# korea_total, korea_scaler = normalizeData(korea_total)
# china_total, china_scaler = normalizeData(china_total)

confirmed_cases_array = np.array([asarray(korea_total), asarray(china_total)])

In [18]:
n_steps = 1
X, y = split_sequence(confirmed_cases_array, n_steps)

In [22]:
confirmed_cases_array.shape

(2, 58, 1)

In [23]:
X.shape

(57, 2, 1, 1)

In [26]:
## Splitting into validation and test sets
number_of_rows = X.shape[0]
n_train = math.ceil(number_of_rows*80/100)
n_test = n_train + math.floor(number_of_rows*10/100)
X_train, y_train, X_val, y_val, X_test, y_test = X[:n_train], y[:n_train], X[n_train:n_test], y[n_train:n_test], X[n_test:], y[n_test:]

In [ ]:
model = Sequential()
model.add(LSTM(50, input_shape=X.shape, return_state=True))
model.add(Dense(3, input_shape=))